# SPDX-FileCopyrightText: 2026 Gauja contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
included:
  - Package.swift
  - ../../tests/codegen/ios
excluded:
  - .build
  - '**/Generated'
disabled_rules:
  - trailing_comma
  - opening_brace
  - identifier_name
line_length:
  warning: 120
  error: 160
file_length:
  warning: 300
  error: 10000
function_body_length:
  warning: 40
  error: 10000
