// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.MediaInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param originalLanguage 
 * @param episodeCount 
 * @param overview 
 * @param originCountry 
 * @param originalName 
 * @param voteCount 
 * @param name 
 * @param mediaType 
 * @param popularity 
 * @param creditId 
 * @param backdropPath 
 * @param firstAirDate 
 * @param voteAverage 
 * @param genreIds 
 * @param posterPath 
 * @param originalTitle 
 * @param video 
 * @param title 
 * @param adult 
 * @param releaseDate 
 * @param character 
 * @param mediaInfo 
 */
@Serializable

data class CreditCast (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "episodeCount")
    val episodeCount: kotlin.Double? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "originCountry")
    val originCountry: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "originalName")
    val originalName: kotlin.String? = null,

    @SerialName(value = "voteCount")
    val voteCount: kotlin.Double? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String? = null,

    @SerialName(value = "popularity")
    val popularity: kotlin.Double? = null,

    @SerialName(value = "creditId")
    val creditId: kotlin.String? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null,

    @SerialName(value = "firstAirDate")
    val firstAirDate: kotlin.String? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: kotlin.Double? = null,

    @SerialName(value = "genreIds")
    val genreIds: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "originalTitle")
    val originalTitle: kotlin.String? = null,

    @SerialName(value = "video")
    val video: kotlin.Boolean? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "releaseDate")
    val releaseDate: kotlin.String? = null,

    @SerialName(value = "character")
    val character: kotlin.String? = null,

    @SerialName(value = "mediaInfo")
    val mediaInfo: MediaInfo? = null

) {
    override fun toString(): String = "[REDACTED]"



}

