// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param botUsername 
 * @param botAvatarUrl 
 * @param webhookUrl 
 * @param webhookRoleId 
 * @param enableMentions 
 */
@Serializable

data class DiscordSettingsOptions (

    @SerialName(value = "botUsername")
    val botUsername: kotlin.String? = null,

    @SerialName(value = "botAvatarUrl")
    val botAvatarUrl: kotlin.String? = null,

    @SerialName(value = "webhookUrl")
    val webhookUrl: kotlin.String? = null,

    @SerialName(value = "webhookRoleId")
    val webhookRoleId: kotlin.String? = null,

    @SerialName(value = "enableMentions")
    val enableMentions: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

