// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param airDate 
 * @param episodeNumber 
 * @param overview 
 * @param productionCode 
 * @param seasonNumber 
 * @param showId 
 * @param stillPath 
 * @param voteAverage 
 * @param voteCount 
 */
@Serializable

data class Episode (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "airDate")
    val airDate: kotlin.String? = null,

    @SerialName(value = "episodeNumber")
    val episodeNumber: kotlin.Double? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "productionCode")
    val productionCode: kotlin.String? = null,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Double? = null,

    @SerialName(value = "showId")
    val showId: kotlin.Double? = null,

    @SerialName(value = "stillPath")
    val stillPath: kotlin.String? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: kotlin.Double? = null,

    @SerialName(value = "voteCount")
    val voteCount: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

