// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param facebookId 
 * @param freebaseId 
 * @param freebaseMid 
 * @param imdbId 
 * @param instagramId 
 * @param tvdbId 
 * @param tvrageId 
 * @param twitterId 
 */
@Serializable

data class ExternalIds (

    @SerialName(value = "facebookId")
    val facebookId: kotlin.String? = null,

    @SerialName(value = "freebaseId")
    val freebaseId: kotlin.String? = null,

    @SerialName(value = "freebaseMid")
    val freebaseMid: kotlin.String? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "instagramId")
    val instagramId: kotlin.String? = null,

    @SerialName(value = "tvdbId")
    val tvdbId: kotlin.Double? = null,

    @SerialName(value = "tvrageId")
    val tvrageId: kotlin.Double? = null,

    @SerialName(value = "twitterId")
    val twitterId: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

