// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.GetBlocklist200ResponseResultsInner
import app.gauja.core.api.models.PageInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param pageInfo 
 * @param results 
 */
@Serializable

data class GetBlocklist200Response (

    @SerialName(value = "pageInfo")
    val pageInfo: PageInfo? = null,

    @SerialName(value = "results")
    val results: kotlin.collections.List<GetBlocklist200ResponseResultsInner>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

