// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param total 
 * @param video 
 * @param audio 
 * @param subtitles 
 * @param others 
 * @param `open` 
 * @param closed 
 */
@Serializable

data class GetIssueCount200Response (

    @SerialName(value = "total")
    val total: kotlin.Double? = null,

    @SerialName(value = "video")
    val video: kotlin.Double? = null,

    @SerialName(value = "audio")
    val audio: kotlin.Double? = null,

    @SerialName(value = "subtitles")
    val subtitles: kotlin.Double? = null,

    @SerialName(value = "others")
    val others: kotlin.Double? = null,

    @SerialName(value = "open")
    val `open`: kotlin.Double? = null,

    @SerialName(value = "closed")
    val closed: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

