// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param year 
 * @param url 
 * @param criticsScore 
 * @param criticsRating 
 * @param audienceScore 
 * @param audienceRating 
 */
@Serializable

data class GetMovieByMovieIdRatings200Response (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "year")
    val year: kotlin.Double? = null,

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "criticsScore")
    val criticsScore: kotlin.Double? = null,

    @SerialName(value = "criticsRating")
    val criticsRating: kotlin.String? = null,

    @SerialName(value = "audienceScore")
    val audienceScore: kotlin.Double? = null,

    @SerialName(value = "audienceRating")
    val audienceRating: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

