// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param playCount7Days 
 * @param playCount30Days 
 * @param playCount 
 * @param users 
 */
@Serializable

data class GetMediaByMediaIdWatchData200ResponseData (

    @SerialName(value = "playCount7Days")
    val playCount7Days: kotlin.Double? = null,

    @SerialName(value = "playCount30Days")
    val playCount30Days: kotlin.Double? = null,

    @SerialName(value = "playCount")
    val playCount: kotlin.Double? = null,

    @SerialName(value = "users")
    val users: kotlin.collections.List<User>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

