// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.CreditCast
import app.gauja.core.api.models.CreditCrew

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cast 
 * @param crew 
 * @param id 
 */
@Serializable

data class GetPersonByPersonIdCombinedCredits200Response (

    @SerialName(value = "cast")
    val cast: kotlin.collections.List<CreditCast>? = null,

    @SerialName(value = "crew")
    val crew: kotlin.collections.List<CreditCrew>? = null,

    @SerialName(value = "id")
    val id: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

