// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param total 
 * @param movie 
 * @param tv 
 * @param pending 
 * @param approved 
 * @param declined 
 * @param processing 
 * @param available 
 * @param completed 
 */
@Serializable

data class GetRequestCount200Response (

    @SerialName(value = "total")
    val total: kotlin.Double? = null,

    @SerialName(value = "movie")
    val movie: kotlin.Double? = null,

    @SerialName(value = "tv")
    val tv: kotlin.Double? = null,

    @SerialName(value = "pending")
    val pending: kotlin.Double? = null,

    @SerialName(value = "approved")
    val approved: kotlin.Double? = null,

    @SerialName(value = "declined")
    val declined: kotlin.Double? = null,

    @SerialName(value = "processing")
    val processing: kotlin.Double? = null,

    @SerialName(value = "available")
    val available: kotlin.Double? = null,

    @SerialName(value = "completed")
    val completed: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

