// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertySize 
 * @param maxSize 
 * @param hits 
 * @param misses 
 * @param failures 
 * @param ipv4Fallbacks 
 * @param hitRate 
 */
@Serializable

data class GetSettingsCache200ResponseDnsCacheStats (

    @SerialName(value = "size")
    val propertySize: kotlin.Double? = null,

    @SerialName(value = "maxSize")
    val maxSize: kotlin.Double? = null,

    @SerialName(value = "hits")
    val hits: kotlin.Double? = null,

    @SerialName(value = "misses")
    val misses: kotlin.Double? = null,

    @SerialName(value = "failures")
    val failures: kotlin.Double? = null,

    @SerialName(value = "ipv4Fallbacks")
    val ipv4Fallbacks: kotlin.Double? = null,

    @SerialName(value = "hitRate")
    val hitRate: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

