// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.GetSettingsCache200ResponseDnsCacheEntriesValue
import app.gauja.core.api.models.GetSettingsCache200ResponseDnsCacheStats

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param stats 
 * @param propertyEntries 
 */
@Serializable

data class GetSettingsCache200ResponseDnsCache (

    @SerialName(value = "stats")
    val stats: GetSettingsCache200ResponseDnsCacheStats? = null,

    @Contextual @SerialName(value = "entries")
    val propertyEntries: kotlin.collections.Map<kotlin.String, GetSettingsCache200ResponseDnsCacheEntriesValue>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

