// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param version 
 * @param commitTag 
 * @param updateAvailable 
 * @param commitsBehind 
 * @param restartRequired 
 */
@Serializable

data class GetStatus200Response (

    @SerialName(value = "version")
    val version: kotlin.String? = null,

    @SerialName(value = "commitTag")
    val commitTag: kotlin.String? = null,

    @SerialName(value = "updateAvailable")
    val updateAvailable: kotlin.Boolean? = null,

    @SerialName(value = "commitsBehind")
    val commitsBehind: kotlin.Double? = null,

    @SerialName(value = "restartRequired")
    val restartRequired: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

