// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param appData 
 * @param appDataPath 
 * @param appDataPermissions 
 */
@Serializable

data class GetStatusAppdata200Response (

    @SerialName(value = "appData")
    val appData: kotlin.Boolean? = null,

    @SerialName(value = "appDataPath")
    val appDataPath: kotlin.String? = null,

    @SerialName(value = "appDataPermissions")
    val appDataPermissions: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

