// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hits 
 * @param misses 
 * @param propertyKeys 
 * @param ksize 
 * @param vsize 
 */
@Serializable

data class GetSettingsCache200ResponseApiCachesInnerStats (

    @SerialName(value = "hits")
    val hits: kotlin.Double? = null,

    @SerialName(value = "misses")
    val misses: kotlin.Double? = null,

    @SerialName(value = "keys")
    val propertyKeys: kotlin.Double? = null,

    @SerialName(value = "ksize")
    val ksize: kotlin.Double? = null,

    @SerialName(value = "vsize")
    val vsize: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

