// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param version 
 * @param totalRequests 
 * @param totalMediaItems 
 * @param tz 
 * @param appDataPath 
 */
@Serializable

data class GetSettingsAbout200Response (

    @SerialName(value = "version")
    val version: kotlin.String? = null,

    @SerialName(value = "totalRequests")
    val totalRequests: kotlin.Double? = null,

    @SerialName(value = "totalMediaItems")
    val totalMediaItems: kotlin.Double? = null,

    @SerialName(value = "tz")
    val tz: kotlin.String? = null,

    @SerialName(value = "appDataPath")
    val appDataPath: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

