// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.GetSettingsCache200ResponseApiCachesInner
import app.gauja.core.api.models.GetSettingsCache200ResponseDnsCache
import app.gauja.core.api.models.GetSettingsCache200ResponseImageCache

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param imageCache 
 * @param dnsCache 
 * @param apiCaches 
 */
@Serializable

data class GetSettingsCache200Response (

    @SerialName(value = "imageCache")
    val imageCache: GetSettingsCache200ResponseImageCache? = null,

    @SerialName(value = "dnsCache")
    val dnsCache: GetSettingsCache200ResponseDnsCache? = null,

    @SerialName(value = "apiCaches")
    val apiCaches: kotlin.collections.List<GetSettingsCache200ResponseApiCachesInner>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

