// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.GetSettingsCache200ResponseDnsCacheEntriesValueAddresses

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addresses 
 * @param activeAddress 
 * @param family 
 * @param age 
 * @param ttl 
 * @param networkErrors 
 * @param hits 
 * @param misses 
 */
@Serializable

data class GetSettingsCache200ResponseDnsCacheEntriesValue (

    @SerialName(value = "addresses")
    val addresses: GetSettingsCache200ResponseDnsCacheEntriesValueAddresses? = null,

    @SerialName(value = "activeAddress")
    val activeAddress: kotlin.String? = null,

    @SerialName(value = "family")
    val family: kotlin.Double? = null,

    @SerialName(value = "age")
    val age: kotlin.Double? = null,

    @SerialName(value = "ttl")
    val ttl: kotlin.Double? = null,

    @SerialName(value = "networkErrors")
    val networkErrors: kotlin.Double? = null,

    @SerialName(value = "hits")
    val hits: kotlin.Double? = null,

    @SerialName(value = "misses")
    val misses: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

