// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.GetUserByUserIdWatchlist200ResponseResultsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param totalPages 
 * @param totalResults 
 * @param results 
 */
@Serializable

data class GetUserByUserIdWatchlist200Response (

    @SerialName(value = "page")
    val page: kotlin.Double? = null,

    @SerialName(value = "totalPages")
    val totalPages: kotlin.Double? = null,

    @SerialName(value = "totalResults")
    val totalResults: kotlin.Double? = null,

    @SerialName(value = "results")
    val results: kotlin.collections.List<GetUserByUserIdWatchlist200ResponseResultsInner>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

