// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param days 
 * @param limit 
 * @param used 
 * @param remaining 
 * @param restricted 
 */
@Serializable

data class GetUserByUserIdQuota200ResponseMovie (

    @SerialName(value = "days")
    val days: kotlin.Double? = null,

    @SerialName(value = "limit")
    val limit: kotlin.Double? = null,

    @SerialName(value = "used")
    val used: kotlin.Double? = null,

    @SerialName(value = "remaining")
    val remaining: kotlin.Double? = null,

    @SerialName(value = "restricted")
    val restricted: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

