// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.IssueComment
import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param issueType 
 * @param media 
 * @param createdBy 
 * @param modifiedBy 
 * @param comments 
 */
@Serializable

data class Issue (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "issueType")
    val issueType: kotlin.Double? = null,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdBy")
    val createdBy: User? = null,

    @SerialName(value = "modifiedBy")
    val modifiedBy: User? = null,

    @SerialName(value = "comments")
    val comments: kotlin.collections.List<IssueComment>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

