// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.JellyfinLibrary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param hostname 
 * @param externalHostname 
 * @param jellyfinForgotPasswordUrl 
 * @param adminUser 
 * @param adminPass 
 * @param libraries 
 * @param serverID 
 */
@Serializable

data class JellyfinSettings (

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "hostname")
    val hostname: kotlin.String? = null,

    @SerialName(value = "externalHostname")
    val externalHostname: kotlin.String? = null,

    @SerialName(value = "jellyfinForgotPasswordUrl")
    val jellyfinForgotPasswordUrl: kotlin.String? = null,

    @SerialName(value = "adminUser")
    val adminUser: kotlin.String? = null,

    @SerialName(value = "adminPass")
    val adminPass: kotlin.String? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<JellyfinLibrary>? = null,

    @SerialName(value = "serverID")
    val serverID: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

