// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKey 
 * @param appLanguage 
 * @param applicationTitle 
 * @param applicationUrl 
 * @param hideAvailable 
 * @param partialRequestsEnabled 
 * @param localLogin 
 * @param mediaServerType 
 * @param newPlexLogin 
 * @param defaultPermissions 
 * @param enableSpecialEpisodes 
 * @param versionCheck 
 */
@Serializable

data class MainSettings (

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String? = null,

    @SerialName(value = "appLanguage")
    val appLanguage: kotlin.String? = null,

    @SerialName(value = "applicationTitle")
    val applicationTitle: kotlin.String? = null,

    @SerialName(value = "applicationUrl")
    val applicationUrl: kotlin.String? = null,

    @SerialName(value = "hideAvailable")
    val hideAvailable: kotlin.Boolean? = null,

    @SerialName(value = "partialRequestsEnabled")
    val partialRequestsEnabled: kotlin.Boolean? = null,

    @SerialName(value = "localLogin")
    val localLogin: kotlin.Boolean? = null,

    @SerialName(value = "mediaServerType")
    val mediaServerType: kotlin.Double? = null,

    @SerialName(value = "newPlexLogin")
    val newPlexLogin: kotlin.Boolean? = null,

    @SerialName(value = "defaultPermissions")
    val defaultPermissions: kotlin.Double? = null,

    @SerialName(value = "enableSpecialEpisodes")
    val enableSpecialEpisodes: kotlin.Boolean? = null,

    @SerialName(value = "versionCheck")
    val versionCheck: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

