// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param status Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
 * @param media 
 * @param createdAt 
 * @param updatedAt 
 * @param requestedBy 
 * @param modifiedBy 
 * @param is4k 
 * @param serverId 
 * @param profileId 
 * @param rootFolder 
 * @param ignoreQuota If true, this request will not count against the user's quota. Requires MANAGE_REQUESTS permission.
 */
@Serializable

data class MediaRequest (

    @SerialName(value = "id")
    val id: kotlin.Double,

    /* Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED */
    @SerialName(value = "status")
    val status: kotlin.Double,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String? = null,

    @SerialName(value = "requestedBy")
    val requestedBy: User? = null,

    @SerialName(value = "modifiedBy")
    val modifiedBy: User? = null,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean? = null,

    @SerialName(value = "serverId")
    val serverId: kotlin.Double? = null,

    @SerialName(value = "profileId")
    val profileId: kotlin.Double? = null,

    @SerialName(value = "rootFolder")
    val rootFolder: kotlin.String? = null,

    /* If true, this request will not count against the user's quota. Requires MANAGE_REQUESTS permission. */
    @SerialName(value = "ignoreQuota")
    val ignoreQuota: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

