// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.ExternalIds
import app.gauja.core.api.models.Genre
import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.MovieDetailsCollection
import app.gauja.core.api.models.MovieDetailsCredits
import app.gauja.core.api.models.MovieDetailsProductionCountriesInner
import app.gauja.core.api.models.MovieDetailsReleases
import app.gauja.core.api.models.ProductionCompany
import app.gauja.core.api.models.RelatedVideo
import app.gauja.core.api.models.SpokenLanguage
import app.gauja.core.api.models.WatchProviders

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param imdbId 
 * @param adult 
 * @param backdropPath 
 * @param posterPath 
 * @param budget 
 * @param genres 
 * @param homepage 
 * @param relatedVideos 
 * @param originalLanguage 
 * @param originalTitle 
 * @param overview 
 * @param popularity 
 * @param productionCompanies 
 * @param productionCountries 
 * @param releaseDate 
 * @param releases 
 * @param revenue 
 * @param runtime 
 * @param spokenLanguages 
 * @param status 
 * @param tagline 
 * @param title 
 * @param video 
 * @param voteAverage 
 * @param voteCount 
 * @param credits 
 * @param collection 
 * @param externalIds 
 * @param mediaInfo 
 * @param watchProviders 
 */
@Serializable

data class MovieDetails (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "budget")
    val budget: kotlin.Double? = null,

    @SerialName(value = "genres")
    val genres: kotlin.collections.List<Genre>? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null,

    @SerialName(value = "relatedVideos")
    val relatedVideos: kotlin.collections.List<RelatedVideo>? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "originalTitle")
    val originalTitle: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "popularity")
    val popularity: kotlin.Double? = null,

    @SerialName(value = "productionCompanies")
    val productionCompanies: kotlin.collections.List<ProductionCompany>? = null,

    @SerialName(value = "productionCountries")
    val productionCountries: kotlin.collections.List<MovieDetailsProductionCountriesInner>? = null,

    @SerialName(value = "releaseDate")
    val releaseDate: kotlin.String? = null,

    @SerialName(value = "releases")
    val releases: MovieDetailsReleases? = null,

    @SerialName(value = "revenue")
    val revenue: kotlin.Double? = null,

    @SerialName(value = "runtime")
    val runtime: kotlin.Double? = null,

    @SerialName(value = "spokenLanguages")
    val spokenLanguages: kotlin.collections.List<SpokenLanguage>? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "tagline")
    val tagline: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "video")
    val video: kotlin.Boolean? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: kotlin.Double? = null,

    @SerialName(value = "voteCount")
    val voteCount: kotlin.Double? = null,

    @SerialName(value = "credits")
    val credits: MovieDetailsCredits? = null,

    @SerialName(value = "collection")
    val collection: MovieDetailsCollection? = null,

    @SerialName(value = "externalIds")
    val externalIds: ExternalIds? = null,

    @SerialName(value = "mediaInfo")
    val mediaInfo: MediaInfo? = null,

    @SerialName(value = "watchProviders")
    val watchProviders: kotlin.collections.List<WatchProviders>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

