// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param certification 
 * @param iso6391 
 * @param note 
 * @param releaseDate 
 * @param type 
 */
@Serializable

data class MovieDetailsReleasesResultsInnerReleaseDatesInner (

    @SerialName(value = "certification")
    val certification: kotlin.String? = null,

    @SerialName(value = "iso_639_1")
    val iso6391: kotlin.String? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @SerialName(value = "release_date")
    val releaseDate: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

