// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.NetworkSettingsDnsCache
import app.gauja.core.api.models.NetworkSettingsProxy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param csrfProtection 
 * @param forceIpv4First 
 * @param trustProxy 
 * @param proxy 
 * @param dnsCache 
 */
@Serializable

data class NetworkSettings (

    @SerialName(value = "csrfProtection")
    val csrfProtection: kotlin.Boolean? = null,

    @SerialName(value = "forceIpv4First")
    val forceIpv4First: kotlin.Boolean? = null,

    @SerialName(value = "trustProxy")
    val trustProxy: kotlin.Boolean? = null,

    @SerialName(value = "proxy")
    val proxy: NetworkSettingsProxy? = null,

    @SerialName(value = "dnsCache")
    val dnsCache: NetworkSettingsDnsCache? = null

) {
    override fun toString(): String = "[REDACTED]"



}

