// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param discord 
 * @param email 
 * @param pushbullet 
 * @param pushover 
 * @param slack 
 * @param telegram 
 * @param webhook 
 * @param webpush 
 */
@Serializable

data class NotificationAgentTypes (

    @SerialName(value = "discord")
    val discord: kotlin.Double? = null,

    @SerialName(value = "email")
    val email: kotlin.Double? = null,

    @SerialName(value = "pushbullet")
    val pushbullet: kotlin.Double? = null,

    @SerialName(value = "pushover")
    val pushover: kotlin.Double? = null,

    @SerialName(value = "slack")
    val slack: kotlin.Double? = null,

    @SerialName(value = "telegram")
    val telegram: kotlin.Double? = null,

    @SerialName(value = "webhook")
    val webhook: kotlin.Double? = null,

    @SerialName(value = "webpush")
    val webpush: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

