// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param emailFrom 
 * @param senderName 
 * @param smtpHost 
 * @param smtpPort 
 * @param secure 
 * @param ignoreTls 
 * @param requireTls 
 * @param authUser 
 * @param authPass 
 * @param allowSelfSigned 
 */
@Serializable

data class NotificationEmailSettingsOptions (

    @SerialName(value = "emailFrom")
    val emailFrom: kotlin.String? = null,

    @SerialName(value = "senderName")
    val senderName: kotlin.String? = null,

    @SerialName(value = "smtpHost")
    val smtpHost: kotlin.String? = null,

    @SerialName(value = "smtpPort")
    val smtpPort: kotlin.Double? = null,

    @SerialName(value = "secure")
    val secure: kotlin.Boolean? = null,

    @SerialName(value = "ignoreTls")
    val ignoreTls: kotlin.Boolean? = null,

    @SerialName(value = "requireTls")
    val requireTls: kotlin.Boolean? = null,

    @SerialName(value = "authUser")
    val authUser: kotlin.String? = null,

    @SerialName(value = "authPass")
    val authPass: kotlin.String? = null,

    @SerialName(value = "allowSelfSigned")
    val allowSelfSigned: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

