// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param topic 
 * @param authMethodUsernamePassword 
 * @param username 
 * @param password 
 * @param authMethodToken 
 * @param token 
 * @param priority 
 * @param locale 
 */
@Serializable

data class NtfySettingsOptions (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "topic")
    val topic: kotlin.String? = null,

    @SerialName(value = "authMethodUsernamePassword")
    val authMethodUsernamePassword: kotlin.Boolean? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "authMethodToken")
    val authMethodToken: kotlin.Boolean? = null,

    @SerialName(value = "token")
    val token: kotlin.String? = null,

    @SerialName(value = "priority")
    val priority: kotlin.Double? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

