// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.PersonResultKnownForInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param profilePath 
 * @param adult 
 * @param mediaType 
 * @param knownFor 
 */
@Serializable

data class PersonResult (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String? = "person",

    @SerialName(value = "knownFor")
    val knownFor: kotlin.collections.List<PersonResultKnownForInner>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

