// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param deathday 
 * @param knownForDepartment 
 * @param alsoKnownAs 
 * @param gender 
 * @param biography 
 * @param popularity 
 * @param placeOfBirth 
 * @param profilePath 
 * @param adult 
 * @param imdbId 
 * @param homepage 
 * @param birthday 
 */
@Serializable

data class PersonDetails (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "deathday")
    val deathday: kotlin.String? = null,

    @SerialName(value = "knownForDepartment")
    val knownForDepartment: kotlin.String? = null,

    @SerialName(value = "alsoKnownAs")
    val alsoKnownAs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "gender")
    val gender: kotlin.Int? = null,

    @SerialName(value = "biography")
    val biography: kotlin.String? = null,

    @SerialName(value = "popularity")
    val popularity: kotlin.Double? = null,

    @SerialName(value = "placeOfBirth")
    val placeOfBirth: kotlin.String? = null,

    @SerialName(value = "profilePath")
    val profilePath: kotlin.String? = null,

    @SerialName(value = "adult")
    val adult: kotlin.Boolean? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null,

    @SerialName(value = "birthday")
    val birthday: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

