// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.MovieResult
import app.gauja.core.api.models.TvResult

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * 
 *
 */
@Serializable(with = PersonResultKnownForInnerSerializer::class)
sealed interface PersonResultKnownForInner {
    @JvmInline
    value class MovieResultValue(val value: MovieResult) : PersonResultKnownForInner

    @JvmInline
    value class TvResultValue(val value: TvResult) : PersonResultKnownForInner

}

object PersonResultKnownForInnerSerializer : KSerializer<PersonResultKnownForInner> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("PersonResultKnownForInner")

    override fun serialize(encoder: Encoder, value: PersonResultKnownForInner) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("PersonResultKnownForInner can only be serialized with Json")

        when (value) {
            is PersonResultKnownForInner.MovieResultValue -> jsonEncoder.encodeSerializableValue(MovieResult.serializer(), value.value)
            is PersonResultKnownForInner.TvResultValue -> jsonEncoder.encodeSerializableValue(TvResult.serializer(), value.value)
        }
    }

    override fun deserialize(decoder: Decoder): PersonResultKnownForInner {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("PersonResultKnownForInner can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<MovieResult>(jsonElement)
                return PersonResultKnownForInner.MovieResultValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as MovieResult: ${e.message}")
            }
        }
        if (jsonElement !is JsonPrimitive) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<TvResult>(jsonElement)
                return PersonResultKnownForInner.TvResultValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as TvResult: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize PersonResultKnownForInner. Tried: ${errorMessages.joinToString(", ")}")
    }
}

