// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.PlexLibrary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param machineId 
 * @param ip 
 * @param port 
 * @param useSsl 
 * @param libraries 
 * @param webAppUrl 
 */
@Serializable

data class PlexSettings (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "machineId")
    val machineId: kotlin.String,

    @SerialName(value = "ip")
    val ip: kotlin.String,

    @SerialName(value = "port")
    val port: kotlin.Double,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean? = null,

    @SerialName(value = "libraries")
    val libraries: kotlin.collections.List<PlexLibrary>? = null,

    @SerialName(value = "webAppUrl")
    val webAppUrl: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

