// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param protocol 
 * @param address 
 * @param port 
 * @param uri 
 * @param local 
 * @param status 
 * @param message 
 */
@Serializable

data class PlexConnection (

    @SerialName(value = "protocol")
    val protocol: kotlin.String,

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "port")
    val port: kotlin.Double,

    @SerialName(value = "uri")
    val uri: kotlin.String,

    @SerialName(value = "local")
    val local: kotlin.Boolean,

    @SerialName(value = "status")
    val status: kotlin.Double? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

