// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param issueType 
 * @param message 
 * @param mediaId 
 * @param userId 
 */
@Serializable

data class PostIssueRequest (

    @SerialName(value = "issueType")
    val issueType: kotlin.Double? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "mediaId")
    val mediaId: kotlin.Double? = null,

    @SerialName(value = "userId")
    val userId: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

