// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.encodeToJsonElement

/**
 * 
 *
 */
@Serializable(with = PostRequestRequestSeasonsSerializer::class)
sealed interface PostRequestRequestSeasons {
    @JvmInline
    value class ListDoubleValue(val value: kotlin.collections.List<kotlin.Double>) : PostRequestRequestSeasons

    @JvmInline
    value class StringValue(val value: kotlin.String) : PostRequestRequestSeasons

}

object PostRequestRequestSeasonsSerializer : KSerializer<PostRequestRequestSeasons> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("PostRequestRequestSeasons")

    override fun serialize(encoder: Encoder, value: PostRequestRequestSeasons) {
        val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("PostRequestRequestSeasons can only be serialized with Json")

        when (value) {
            is PostRequestRequestSeasons.ListDoubleValue -> jsonEncoder.encodeJsonElement(jsonEncoder.json.encodeToJsonElement(value.value))
            is PostRequestRequestSeasons.StringValue -> jsonEncoder.encodeString(value.value)
        }
    }

    override fun deserialize(decoder: Decoder): PostRequestRequestSeasons {
        val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("PostRequestRequestSeasons can only be deserialized with Json")
        val jsonElement = jsonDecoder.decodeJsonElement()

        val errorMessages = mutableListOf<String>()

        if (jsonElement is JsonArray) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.collections.List<kotlin.Double>>(jsonElement)
                return PostRequestRequestSeasons.ListDoubleValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.collections.List<kotlin.Double>: ${e.message}")
            }
        }
        if (jsonElement is JsonPrimitive && jsonElement.isString) {
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<kotlin.String>(jsonElement)
                return PostRequestRequestSeasons.StringValue(instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as kotlin.String: ${e.message}")
            }
        }

        throw SerializationException("Cannot deserialize PostRequestRequestSeasons. Tried: ${errorMessages.joinToString(", ")}")
    }
}

