// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hostname 
 * @param port 
 * @param apiKey 
 * @param useSsl 
 * @param baseUrl 
 */
@Serializable

data class PostSettingsSonarrTestRequest (

    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    @SerialName(value = "port")
    val port: kotlin.Double,

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean,

    @SerialName(value = "baseUrl")
    val baseUrl: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

