// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param initialized 
 * @param plexClientIdentifier Instance Plex OAuth client identifier
 * @param applicationTitle 
 * @param applicationUrl 
 * @param hideAvailable 
 * @param hideBlocklisted 
 * @param localLogin 
 * @param mediaServerLogin 
 * @param movie4kEnabled 
 * @param series4kEnabled 
 * @param discoverRegion 
 * @param streamingRegion 
 * @param originalLanguage 
 * @param mediaServerType 
 * @param jellyfinExternalHost 
 * @param jellyfinForgotPasswordUrl 
 * @param partialRequestsEnabled 
 * @param enableSpecialEpisodes 
 * @param cacheImages 
 * @param vapidPublic 
 * @param enablePushRegistration 
 * @param locale 
 * @param emailEnabled 
 * @param userEmailRequired 
 * @param newPlexLogin 
 * @param youtubeUrl 
 * @param versionCheck 
 */
@Serializable

data class PublicSettings (

    @SerialName(value = "initialized")
    val initialized: kotlin.Boolean,

    /* Instance Plex OAuth client identifier */
    @Contextual @SerialName(value = "plexClientIdentifier")
    val plexClientIdentifier: java.util.UUID,

    @SerialName(value = "applicationTitle")
    val applicationTitle: kotlin.String? = null,

    @SerialName(value = "applicationUrl")
    val applicationUrl: kotlin.String? = null,

    @SerialName(value = "hideAvailable")
    val hideAvailable: kotlin.Boolean? = null,

    @SerialName(value = "hideBlocklisted")
    val hideBlocklisted: kotlin.Boolean? = null,

    @SerialName(value = "localLogin")
    val localLogin: kotlin.Boolean? = null,

    @SerialName(value = "mediaServerLogin")
    val mediaServerLogin: kotlin.Boolean? = null,

    @SerialName(value = "movie4kEnabled")
    val movie4kEnabled: kotlin.Boolean? = null,

    @SerialName(value = "series4kEnabled")
    val series4kEnabled: kotlin.Boolean? = null,

    @SerialName(value = "discoverRegion")
    val discoverRegion: kotlin.String? = null,

    @SerialName(value = "streamingRegion")
    val streamingRegion: kotlin.String? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "mediaServerType")
    val mediaServerType: kotlin.Double? = null,

    @SerialName(value = "jellyfinExternalHost")
    val jellyfinExternalHost: kotlin.String? = null,

    @SerialName(value = "jellyfinForgotPasswordUrl")
    val jellyfinForgotPasswordUrl: kotlin.String? = null,

    @SerialName(value = "partialRequestsEnabled")
    val partialRequestsEnabled: kotlin.Boolean? = null,

    @SerialName(value = "enableSpecialEpisodes")
    val enableSpecialEpisodes: kotlin.Boolean? = null,

    @SerialName(value = "cacheImages")
    val cacheImages: kotlin.Boolean? = null,

    @SerialName(value = "vapidPublic")
    val vapidPublic: kotlin.String? = null,

    @SerialName(value = "enablePushRegistration")
    val enablePushRegistration: kotlin.Boolean? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @SerialName(value = "emailEnabled")
    val emailEnabled: kotlin.Boolean? = null,

    @SerialName(value = "userEmailRequired")
    val userEmailRequired: kotlin.Boolean? = null,

    @SerialName(value = "newPlexLogin")
    val newPlexLogin: kotlin.Boolean? = null,

    @SerialName(value = "youtubeUrl")
    val youtubeUrl: kotlin.String? = null,

    @SerialName(value = "versionCheck")
    val versionCheck: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

