// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mediaType 
 * @param seasons 
 * @param is4k 
 * @param serverId 
 * @param profileId 
 * @param rootFolder 
 * @param languageProfileId 
 * @param userId 
 */
@Serializable

data class PutRequestByRequestIdRequest (

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String,

    @SerialName(value = "seasons")
    val seasons: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean? = null,

    @SerialName(value = "serverId")
    val serverId: kotlin.Double? = null,

    @SerialName(value = "profileId")
    val profileId: kotlin.Double? = null,

    @SerialName(value = "rootFolder")
    val rootFolder: kotlin.String? = null,

    @SerialName(value = "languageProfileId")
    val languageProfileId: kotlin.Double? = null,

    @SerialName(value = "userId")
    val userId: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

