// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param hostname 
 * @param port 
 * @param apiKey 
 * @param useSsl 
 * @param activeProfileId 
 * @param activeProfileName 
 * @param activeDirectory 
 * @param is4k 
 * @param minimumAvailability 
 * @param isDefault 
 * @param id 
 * @param baseUrl 
 * @param externalUrl 
 * @param syncEnabled 
 * @param preventSearch 
 */
@Serializable

data class RadarrSettings (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    @SerialName(value = "port")
    val port: kotlin.Double,

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean,

    @SerialName(value = "activeProfileId")
    val activeProfileId: kotlin.Double,

    @SerialName(value = "activeProfileName")
    val activeProfileName: kotlin.String,

    @SerialName(value = "activeDirectory")
    val activeDirectory: kotlin.String,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean,

    @SerialName(value = "minimumAvailability")
    val minimumAvailability: kotlin.String,

    @SerialName(value = "isDefault")
    val isDefault: kotlin.Boolean,

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "baseUrl")
    val baseUrl: kotlin.String? = null,

    @SerialName(value = "externalUrl")
    val externalUrl: kotlin.String? = null,

    @SerialName(value = "syncEnabled")
    val syncEnabled: kotlin.Boolean? = null,

    @SerialName(value = "preventSearch")
    val preventSearch: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

