// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param url 
 * @param key 
 * @param name 
 * @param propertySize 
 * @param type 
 * @param site 
 */
@Serializable

data class RelatedVideo (

    @SerialName(value = "url")
    val url: kotlin.String? = null,

    @SerialName(value = "key")
    val key: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "size")
    val propertySize: kotlin.Double? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "site")
    val site: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

