// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.Episode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param airDate 
 * @param episodeCount 
 * @param name 
 * @param overview 
 * @param posterPath 
 * @param seasonNumber 
 * @param episodes 
 */
@Serializable

data class Season (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "airDate")
    val airDate: kotlin.String? = null,

    @SerialName(value = "episodeCount")
    val episodeCount: kotlin.Double? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Double? = null,

    @SerialName(value = "episodes")
    val episodes: kotlin.collections.List<Episode>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

