// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ignoreEpisodesWithFiles 
 * @param ignoreEpisodesWithoutFiles 
 * @param searchForMissingEpisodes 
 */
@Serializable

data class SonarrSeriesAddOptionsInner (

    @SerialName(value = "ignoreEpisodesWithFiles")
    val ignoreEpisodesWithFiles: kotlin.Boolean? = null,

    @SerialName(value = "ignoreEpisodesWithoutFiles")
    val ignoreEpisodesWithoutFiles: kotlin.Boolean? = null,

    @SerialName(value = "searchForMissingEpisodes")
    val searchForMissingEpisodes: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

