// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.SonarrSeriesAddOptionsInner
import app.gauja.core.api.models.SonarrSeriesImagesInner
import app.gauja.core.api.models.SonarrSeriesRatingsInner
import app.gauja.core.api.models.SonarrSeriesSeasonsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param sortTitle 
 * @param seasonCount 
 * @param status 
 * @param overview 
 * @param network 
 * @param airTime 
 * @param images 
 * @param remotePoster 
 * @param seasons 
 * @param year 
 * @param path 
 * @param profileId 
 * @param languageProfileId 
 * @param seasonFolder 
 * @param monitored 
 * @param useSceneNumbering 
 * @param runtime 
 * @param tvdbId 
 * @param tvRageId 
 * @param tvMazeId 
 * @param firstAired 
 * @param lastInfoSync 
 * @param seriesType 
 * @param cleanTitle 
 * @param imdbId 
 * @param titleSlug 
 * @param certification 
 * @param genres 
 * @param tags 
 * @param added 
 * @param ratings 
 * @param qualityProfileId 
 * @param id 
 * @param rootFolderPath 
 * @param addOptions 
 */
@Serializable

data class SonarrSeries (

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "sortTitle")
    val sortTitle: kotlin.String? = null,

    @SerialName(value = "seasonCount")
    val seasonCount: kotlin.Double? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "network")
    val network: kotlin.String? = null,

    @SerialName(value = "airTime")
    val airTime: kotlin.String? = null,

    @SerialName(value = "images")
    val images: kotlin.collections.List<SonarrSeriesImagesInner>? = null,

    @SerialName(value = "remotePoster")
    val remotePoster: kotlin.String? = null,

    @SerialName(value = "seasons")
    val seasons: kotlin.collections.List<SonarrSeriesSeasonsInner>? = null,

    @SerialName(value = "year")
    val year: kotlin.Double? = null,

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    @SerialName(value = "profileId")
    val profileId: kotlin.Double? = null,

    @SerialName(value = "languageProfileId")
    val languageProfileId: kotlin.Double? = null,

    @SerialName(value = "seasonFolder")
    val seasonFolder: kotlin.Boolean? = null,

    @SerialName(value = "monitored")
    val monitored: kotlin.Boolean? = null,

    @SerialName(value = "useSceneNumbering")
    val useSceneNumbering: kotlin.Boolean? = null,

    @SerialName(value = "runtime")
    val runtime: kotlin.Double? = null,

    @SerialName(value = "tvdbId")
    val tvdbId: kotlin.Double? = null,

    @SerialName(value = "tvRageId")
    val tvRageId: kotlin.Double? = null,

    @SerialName(value = "tvMazeId")
    val tvMazeId: kotlin.Double? = null,

    @SerialName(value = "firstAired")
    val firstAired: kotlin.String? = null,

    @SerialName(value = "lastInfoSync")
    val lastInfoSync: kotlin.String? = null,

    @SerialName(value = "seriesType")
    val seriesType: kotlin.String? = null,

    @SerialName(value = "cleanTitle")
    val cleanTitle: kotlin.String? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "titleSlug")
    val titleSlug: kotlin.String? = null,

    @SerialName(value = "certification")
    val certification: kotlin.String? = null,

    @SerialName(value = "genres")
    val genres: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "added")
    val added: kotlin.String? = null,

    @SerialName(value = "ratings")
    val ratings: kotlin.collections.List<SonarrSeriesRatingsInner>? = null,

    @SerialName(value = "qualityProfileId")
    val qualityProfileId: kotlin.Double? = null,

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "rootFolderPath")
    val rootFolderPath: kotlin.String? = null,

    @SerialName(value = "addOptions")
    val addOptions: kotlin.collections.List<SonarrSeriesAddOptionsInner>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

