// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param hostname 
 * @param port 
 * @param apiKey 
 * @param useSsl 
 * @param activeProfileId 
 * @param activeProfileName 
 * @param activeDirectory 
 * @param is4k 
 * @param enableSeasonFolders 
 * @param isDefault 
 * @param id 
 * @param baseUrl 
 * @param activeLanguageProfileId 
 * @param activeAnimeProfileId 
 * @param activeAnimeLanguageProfileId 
 * @param activeAnimeProfileName 
 * @param activeAnimeDirectory 
 * @param externalUrl 
 * @param syncEnabled 
 * @param preventSearch 
 */
@Serializable

data class SonarrSettings (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "hostname")
    val hostname: kotlin.String,

    @SerialName(value = "port")
    val port: kotlin.Double,

    @SerialName(value = "apiKey")
    val apiKey: kotlin.String,

    @SerialName(value = "useSsl")
    val useSsl: kotlin.Boolean,

    @SerialName(value = "activeProfileId")
    val activeProfileId: kotlin.Double,

    @SerialName(value = "activeProfileName")
    val activeProfileName: kotlin.String,

    @SerialName(value = "activeDirectory")
    val activeDirectory: kotlin.String,

    @SerialName(value = "is4k")
    val is4k: kotlin.Boolean,

    @SerialName(value = "enableSeasonFolders")
    val enableSeasonFolders: kotlin.Boolean,

    @SerialName(value = "isDefault")
    val isDefault: kotlin.Boolean,

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "baseUrl")
    val baseUrl: kotlin.String? = null,

    @SerialName(value = "activeLanguageProfileId")
    val activeLanguageProfileId: kotlin.Double? = null,

    @SerialName(value = "activeAnimeProfileId")
    val activeAnimeProfileId: kotlin.Double? = null,

    @SerialName(value = "activeAnimeLanguageProfileId")
    val activeAnimeLanguageProfileId: kotlin.Double? = null,

    @SerialName(value = "activeAnimeProfileName")
    val activeAnimeProfileName: kotlin.String? = null,

    @SerialName(value = "activeAnimeDirectory")
    val activeAnimeDirectory: kotlin.String? = null,

    @SerialName(value = "externalUrl")
    val externalUrl: kotlin.String? = null,

    @SerialName(value = "syncEnabled")
    val syncEnabled: kotlin.Boolean? = null,

    @SerialName(value = "preventSearch")
    val preventSearch: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

