// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param botUsername 
 * @param botAPI 
 * @param chatId 
 * @param messageThreadId 
 * @param sendSilently 
 */
@Serializable

data class TelegramSettingsOptions (

    @SerialName(value = "botUsername")
    val botUsername: kotlin.String? = null,

    @SerialName(value = "botAPI")
    val botAPI: kotlin.String? = null,

    @SerialName(value = "chatId")
    val chatId: kotlin.String? = null,

    @SerialName(value = "messageThreadId")
    val messageThreadId: kotlin.String? = null,

    @SerialName(value = "sendSilently")
    val sendSilently: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

