// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.Episode
import app.gauja.core.api.models.ExternalIds
import app.gauja.core.api.models.Genre
import app.gauja.core.api.models.Keyword
import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.MovieDetailsCredits
import app.gauja.core.api.models.MovieDetailsProductionCountriesInner
import app.gauja.core.api.models.ProductionCompany
import app.gauja.core.api.models.Season
import app.gauja.core.api.models.SpokenLanguage
import app.gauja.core.api.models.TvDetailsContentRatings
import app.gauja.core.api.models.TvDetailsCreatedByInner
import app.gauja.core.api.models.WatchProviders

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param backdropPath 
 * @param posterPath 
 * @param contentRatings 
 * @param createdBy 
 * @param episodeRunTime 
 * @param firstAirDate 
 * @param genres 
 * @param homepage 
 * @param inProduction 
 * @param languages 
 * @param lastAirDate 
 * @param lastEpisodeToAir 
 * @param name 
 * @param nextEpisodeToAir 
 * @param networks 
 * @param numberOfEpisodes 
 * @param numberOfSeason 
 * @param originCountry 
 * @param originalLanguage 
 * @param originalName 
 * @param overview 
 * @param popularity 
 * @param productionCompanies 
 * @param productionCountries 
 * @param spokenLanguages 
 * @param seasons 
 * @param status 
 * @param tagline 
 * @param type 
 * @param voteAverage 
 * @param voteCount 
 * @param credits 
 * @param externalIds 
 * @param keywords 
 * @param mediaInfo 
 * @param watchProviders 
 */
@Serializable

data class TvDetails (

    @SerialName(value = "id")
    val id: kotlin.Double? = null,

    @SerialName(value = "backdropPath")
    val backdropPath: kotlin.String? = null,

    @SerialName(value = "posterPath")
    val posterPath: kotlin.String? = null,

    @SerialName(value = "contentRatings")
    val contentRatings: TvDetailsContentRatings? = null,

    @SerialName(value = "createdBy")
    val createdBy: kotlin.collections.List<TvDetailsCreatedByInner>? = null,

    @SerialName(value = "episodeRunTime")
    val episodeRunTime: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "firstAirDate")
    val firstAirDate: kotlin.String? = null,

    @SerialName(value = "genres")
    val genres: kotlin.collections.List<Genre>? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null,

    @SerialName(value = "inProduction")
    val inProduction: kotlin.Boolean? = null,

    @SerialName(value = "languages")
    val languages: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "lastAirDate")
    val lastAirDate: kotlin.String? = null,

    @SerialName(value = "lastEpisodeToAir")
    val lastEpisodeToAir: Episode? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "nextEpisodeToAir")
    val nextEpisodeToAir: Episode? = null,

    @SerialName(value = "networks")
    val networks: kotlin.collections.List<ProductionCompany>? = null,

    @SerialName(value = "numberOfEpisodes")
    val numberOfEpisodes: kotlin.Double? = null,

    @SerialName(value = "numberOfSeason")
    val numberOfSeason: kotlin.Double? = null,

    @SerialName(value = "originCountry")
    val originCountry: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    @SerialName(value = "originalName")
    val originalName: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "popularity")
    val popularity: kotlin.Double? = null,

    @SerialName(value = "productionCompanies")
    val productionCompanies: kotlin.collections.List<ProductionCompany>? = null,

    @SerialName(value = "productionCountries")
    val productionCountries: kotlin.collections.List<MovieDetailsProductionCountriesInner>? = null,

    @SerialName(value = "spokenLanguages")
    val spokenLanguages: kotlin.collections.List<SpokenLanguage>? = null,

    @SerialName(value = "seasons")
    val seasons: kotlin.collections.List<Season>? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "tagline")
    val tagline: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "voteAverage")
    val voteAverage: kotlin.Double? = null,

    @SerialName(value = "voteCount")
    val voteCount: kotlin.Double? = null,

    @SerialName(value = "credits")
    val credits: MovieDetailsCredits? = null,

    @SerialName(value = "externalIds")
    val externalIds: ExternalIds? = null,

    @SerialName(value = "keywords")
    val keywords: kotlin.collections.List<Keyword>? = null,

    @SerialName(value = "mediaInfo")
    val mediaInfo: MediaInfo? = null,

    @SerialName(value = "watchProviders")
    val watchProviders: kotlin.collections.List<WatchProviders>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

