// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param username 
 * @param email 
 * @param locale 
 * @param discoverRegion 
 * @param streamingRegion 
 * @param originalLanguage 
 * @param movieQuotaLimit Maximum number of movie requests allowed
 * @param movieQuotaDays Time period in days for movie quota
 * @param tvQuotaLimit Maximum number of TV requests allowed
 * @param tvQuotaDays Time period in days for TV quota
 * @param globalMovieQuotaDays Global movie quota days setting
 * @param globalMovieQuotaLimit Global movie quota limit setting
 * @param globalTvQuotaLimit Global TV quota limit setting
 * @param globalTvQuotaDays Global TV quota days setting
 * @param watchlistSyncMovies Enable watchlist sync for movies
 * @param watchlistSyncTv Enable watchlist sync for TV
 */
@Serializable

data class UserSettings (

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @SerialName(value = "discoverRegion")
    val discoverRegion: kotlin.String? = null,

    @SerialName(value = "streamingRegion")
    val streamingRegion: kotlin.String? = null,

    @SerialName(value = "originalLanguage")
    val originalLanguage: kotlin.String? = null,

    /* Maximum number of movie requests allowed */
    @SerialName(value = "movieQuotaLimit")
    val movieQuotaLimit: kotlin.Double? = null,

    /* Time period in days for movie quota */
    @SerialName(value = "movieQuotaDays")
    val movieQuotaDays: kotlin.Double? = null,

    /* Maximum number of TV requests allowed */
    @SerialName(value = "tvQuotaLimit")
    val tvQuotaLimit: kotlin.Double? = null,

    /* Time period in days for TV quota */
    @SerialName(value = "tvQuotaDays")
    val tvQuotaDays: kotlin.Double? = null,

    /* Global movie quota days setting */
    @SerialName(value = "globalMovieQuotaDays")
    val globalMovieQuotaDays: kotlin.Double? = null,

    /* Global movie quota limit setting */
    @SerialName(value = "globalMovieQuotaLimit")
    val globalMovieQuotaLimit: kotlin.Double? = null,

    /* Global TV quota limit setting */
    @SerialName(value = "globalTvQuotaLimit")
    val globalTvQuotaLimit: kotlin.Double? = null,

    /* Global TV quota days setting */
    @SerialName(value = "globalTvQuotaDays")
    val globalTvQuotaDays: kotlin.Double? = null,

    /* Enable watchlist sync for movies */
    @SerialName(value = "watchlistSyncMovies")
    val watchlistSyncMovies: kotlin.Boolean? = null,

    /* Enable watchlist sync for TV */
    @SerialName(value = "watchlistSyncTv")
    val watchlistSyncTv: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

