// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param email 
 * @param createdAt 
 * @param updatedAt 
 * @param username 
 * @param plexUsername 
 * @param plexToken 
 * @param jellyfinAuthToken 
 * @param userType 
 * @param permissions 
 * @param avatar 
 * @param requestCount 
 */
@Serializable

data class User (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String? = null,

    @SerialName(value = "plexUsername")
    val plexUsername: kotlin.String? = null,

    @SerialName(value = "plexToken")
    val plexToken: kotlin.String? = null,

    @SerialName(value = "jellyfinAuthToken")
    val jellyfinAuthToken: kotlin.String? = null,

    @SerialName(value = "userType")
    val userType: kotlin.Int? = null,

    @SerialName(value = "permissions")
    val permissions: kotlin.Double? = null,

    @SerialName(value = "avatar")
    val avatar: kotlin.String? = null,

    @SerialName(value = "requestCount")
    val requestCount: kotlin.Double? = null

) {
    override fun toString(): String = "[REDACTED]"



}

