// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tmdbId 
 * @param mediaType 
 * @param ratingKey 
 * @param title 
 */
@Serializable

data class WatchlistRequest (

    @SerialName(value = "tmdbId")
    val tmdbId: kotlin.Double,

    @SerialName(value = "mediaType")
    val mediaType: kotlin.String,

    @SerialName(value = "ratingKey")
    val ratingKey: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null

) {
    override fun toString(): String = "[REDACTED]"



}

