// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.WatchProviderDetails

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param iso31661 
 * @param link 
 * @param buy 
 * @param flatrate 
 */
@Serializable

data class WatchProviders (

    @SerialName(value = "iso_3166_1")
    val iso31661: kotlin.String,

    @SerialName(value = "link")
    val link: kotlin.String? = null,

    @SerialName(value = "buy")
    val buy: kotlin.collections.List<WatchProviderDetails>? = null,

    @SerialName(value = "flatrate")
    val flatrate: kotlin.collections.List<WatchProviderDetails>? = null

) {
    override fun toString(): String = "[REDACTED]"



}

