// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models

import app.gauja.core.api.models.MediaInfo
import app.gauja.core.api.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param tmdbId 
 * @param ratingKey 
 * @param type 
 * @param title 
 * @param media 
 * @param createdAt 
 * @param updatedAt 
 * @param requestedBy 
 */
@Serializable

data class Watchlist (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "tmdbId")
    val tmdbId: kotlin.Double? = null,

    @SerialName(value = "ratingKey")
    val ratingKey: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "media")
    val media: MediaInfo? = null,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String? = null,

    @SerialName(value = "requestedBy")
    val requestedBy: User? = null

) {
    override fun toString(): String = "[REDACTED]"



}

