// SPDX-FileCopyrightText: 2026 Gauja contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED — do not edit. Run tools/codegen/generate.sh.
/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.gauja.core.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param webhookUrl 
 * @param authHeader 
 * @param jsonPayload 
 * @param supportVariables 
 */
@Serializable

data class WebhookSettingsOptions (

    @SerialName(value = "webhookUrl")
    val webhookUrl: kotlin.String? = null,

    @SerialName(value = "authHeader")
    val authHeader: kotlin.String? = null,

    @SerialName(value = "jsonPayload")
    val jsonPayload: kotlin.String? = null,

    @SerialName(value = "supportVariables")
    val supportVariables: kotlin.Boolean? = null

) {
    override fun toString(): String = "[REDACTED]"



}

